/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bangundatar_202557201005;

/**
 *
 * @author ANGGUN Z
 */
public class beranda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(beranda.class.getName());

    /**
     * Creates new form beranda
     */
    public beranda() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSegitiga = new javax.swing.JButton();
        btnPersegiPanjang = new javax.swing.JButton();
        btnLingkaran = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnPersegi = new javax.swing.JButton();
        btnBelahKetupat = new javax.swing.JButton();
        btnTrapesium = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("beranda");
        setBackground(new java.awt.Color(138, 166, 132));

        jLabel1.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(168, 197, 160));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplikasi Bangun Datar");

        btnSegitiga.setBackground(new java.awt.Color(248, 247, 244));
        btnSegitiga.setForeground(new java.awt.Color(168, 197, 160));
        btnSegitiga.setText("Segitiga");
        btnSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSegitigaActionPerformed(evt);
            }
        });

        btnPersegiPanjang.setBackground(new java.awt.Color(248, 247, 244));
        btnPersegiPanjang.setForeground(new java.awt.Color(168, 197, 160));
        btnPersegiPanjang.setText("Persegi Panjang");
        btnPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersegiPanjangActionPerformed(evt);
            }
        });

        btnLingkaran.setBackground(new java.awt.Color(248, 247, 244));
        btnLingkaran.setForeground(new java.awt.Color(168, 197, 160));
        btnLingkaran.setText("Lingkaran");
        btnLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLingkaranActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(248, 247, 244));
        btnExit.setForeground(new java.awt.Color(168, 197, 160));
        btnExit.setText("Keluar");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnPersegi.setBackground(new java.awt.Color(248, 247, 244));
        btnPersegi.setForeground(new java.awt.Color(168, 197, 160));
        btnPersegi.setText("Persegi");
        btnPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersegiActionPerformed(evt);
            }
        });

        btnBelahKetupat.setBackground(new java.awt.Color(248, 247, 244));
        btnBelahKetupat.setForeground(new java.awt.Color(168, 197, 160));
        btnBelahKetupat.setText("Belah Ketupat");
        btnBelahKetupat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBelahKetupatActionPerformed(evt);
            }
        });

        btnTrapesium.setBackground(new java.awt.Color(248, 247, 244));
        btnTrapesium.setForeground(new java.awt.Color(168, 197, 160));
        btnTrapesium.setText("Trapesium");
        btnTrapesium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrapesiumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExit)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPersegiPanjang))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTrapesium, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(btnPersegi, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(btnBelahKetupat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSegitiga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLingkaran)
                            .addComponent(btnTrapesium))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnBelahKetupat)
                                    .addComponent(btnPersegiPanjang)))
                            .addComponent(btnPersegi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)))
                .addComponent(btnExit)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersegiPanjangActionPerformed
        // TODO add your handling code here:
        new PersegiPanjang().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnPersegiPanjangActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSegitigaActionPerformed
        // TODO add your handling code here:
        new segitiga().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSegitigaActionPerformed

    private void btnLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLingkaranActionPerformed
        // TODO add your handling code here:
        new Lingkaran1().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLingkaranActionPerformed

    private void btnPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersegiActionPerformed
        // TODO add your handling code here:
        new Persegi().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPersegiActionPerformed

    private void btnBelahKetupatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBelahKetupatActionPerformed
        // TODO add your handling code here:
        new belahKetupat().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnBelahKetupatActionPerformed

    private void btnTrapesiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrapesiumActionPerformed
        // TODO add your handling code here:
        new trapesium().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnTrapesiumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new beranda().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBelahKetupat;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLingkaran;
    private javax.swing.JButton btnPersegi;
    private javax.swing.JButton btnPersegiPanjang;
    private javax.swing.JButton btnSegitiga;
    private javax.swing.JButton btnTrapesium;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
